### ISSUE TITLE
Unicode characters in query parameters are wrong encoded

### ISSUE THREAD

**Issue by andrueastman** [std-uritemplate/std-uritemplate#114]
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2251

The `AddExpandedValue` splits string values into individual charaters and then calls `Uri.EscapeDataString` on each character. This seems to bring an issue in the event a unicode character is passed resulting to different result produced.

https://github.com/std-uritemplate/std-uritemplate/blob/94172c186b2c11c95aa51493d8e1518396a680df/csharp/Std.UriTemplate.cs#L313

The result of encoding the example string `startswith(displayName, '🛡️_')` is not as expected.

Expected is : `startswith%28displayName%2C%20%27%F0%9F%9B%A1%EF%B8%8F_%27%29`
Result is : `startswith%28displayName%2C %27%EF%BF%BD%EF%BF%BD️_%27%29`  

The correct result is produced when calling `Uri.EscapeDataString` on the entire input string and not character by character.

**Comment by andreaTP** [comment]
Thanks for opening this issue @andrueastman , I noticed this issue while reviewing the Vert.X UriTemplate implementation and the current implementation is not passing tests like this: https://github.com/eclipse-vertx/vertx-uri-template/blob/36cf6933a8842c7e295948c930b119bcbca5a484/src/test/java/io/vertx/uritemplate/ExpansionTest.java#L41

I think we also have an opportunity to improve performance here by removing the standard library call to the encoder and having a plain implementation in code like this:
https://github.com/eclipse-vertx/vertx-uri-template/blob/36cf6933a8842c7e295948c930b119bcbca5a484/src/main/java/io/vertx/uritemplate/impl/UriTemplateImpl.java#L485

Questions:

- are you willing to provide a fix? (at least in one of the languages)
- how urgent is this on your side?

**Comment by andrueastman** [comment]
Thanks for the pointer here @andreaTP.

Given that the issue is understood here, I'm happy to be assigned this one to take this on across the languages if that's okay.

**Comment by andreaTP** [comment]
Sounds great! Thanks a lot for taking this @andrueastman !

In the interest of your time, this is the process I used for this kind of change:

- add additional tests to cover the cases [here](https://github.com/std-uritemplate/std-uritemplate/tree/main/uritemplate-test-additional)
- implement the fix in one language
- open a Draft PR to gather feedback on the approach and tradeoffs
- port the fix to all of the languages

Additional note:
The Go implementation is currently using `rune` and should be able to easily deal with unicode characters, but, iterating on `byte`s is faster(according to Go experts), I will be supportive of moving to `byte` and getting the implementation as uniform as possible with the other languages.

**Comment by andreaTP** [comment]
@andrueastman I noticed that this Issue went a bit stale and took a stab at the fix in #118 , please let me know what you think about it!
