### ISSUE TITLE
Verify the publisher for Dart

### ISSUE THREAD

**Issue by andreaTP** [std-uritemplate/std-uritemplate#127]
We are now publishing a Dart package and this is the relevant documentation:
https://dart.dev/tools/pub/publishing

Currently, we don't have a "Verified publisher".
I have attempted to follow it, but I have been hitting a few rough edges:

- I have created a free sub-domain here: https://github.com/proj-at/subdomains/pull/23
- I have verified the property ( std_uritemplate.proj.sbs ) using the Google Search Console
- Trying to create a publisher with the subdomain here: https://pub.dev/create-publisher doesn't work as(seems like) only top level domains are allowed

The next step would be to reach out to the support of `pub.dev` (email: `support@pub.dev`).

@ricardoboss would you be up on digging into this one on our behalf?

**Comment by ricardoboss** [comment]
Sure! Is there a way other than GitHub where I can reach you in case I need further information?

**Comment by andreaTP** [comment]
Thanks @ricardoboss ! My private email is public on my GH profile, feel free to write there 👍

**Comment by ricardoboss** [comment]
I contacted the pub.dev support but haven't heard back yet. I will try again later this week.

**Comment by ricardoboss** [comment]
Small update: we have heard back from the pub.dev support and it seems that the domain we want to register as a verified published cannot contain underscores.

@andreaTP has already fixed this at the proj-at repository here: https://github.com/proj-at/subdomains/pull/24. Thanks!

Next step would be to retry verifying that domain and then use it to verify the publisher on pub.dev.

**Comment by andreaTP** [comment]
Thanks for following up @ricardoboss , I verified the domain again and this time it went through!

You can check here: https://pub.dev/packages/std_uritemplate that the publisher is now certified.

I can do an extra release to verify that everything is still aligned, but it seems unnecessary.

**Comment by ricardoboss** [comment]
Nice! This can be closed then.
