### ISSUE TITLE
Guid values are not supported

### ISSUE THREAD

**Issue by baywet** [std-uritemplate/std-uritemplate#140]
Originally reported https://github.com/microsoft/kiota/issues/4335
https://github.com/std-uritemplate/std-uritemplate/blob/95b7aceaddf3c0ccc02d0e8cf4d7c2a90b423098/csharp/Std.UriTemplate.cs#L470
https://github.com/std-uritemplate/std-uritemplate/blob/95b7aceaddf3c0ccc02d0e8cf4d7c2a90b423098/java/src/main/java/io/github/stduritemplate/StdUriTemplate.java#L403
https://github.com/std-uritemplate/std-uritemplate/blob/95b7aceaddf3c0ccc02d0e8cf4d7c2a90b423098/typescript/src/index.ts#L398

etc...

Are not converting a guid/uuid value to string. While we could implement that conversion in kiota abstractions, it'd be more consistent to do it here.

Happy to implement that myself, or to hand it over to somebody else if there are any volunteers.

**Comment by andreaTP** [comment]
No super strong opinion on where we should do it, I'm ok with doing it here if anyone volunteers to do the job.

Probably we should have a "list of supported native types" in the Readme though ...

**Comment by illunix** [comment]
![image](https://github.com/std-uritemplate/std-uritemplate/assets/42069493/e6fd412c-010a-4f5d-a92b-a749d59b43ca)
I think there should be if with calue == Guid and that's it

**Comment by andreaTP** [comment]
> I think there should be if with calue == Guid and that's it

Correct, but:
- for all the languages
- tested as we test the native dates

**Comment by baywet** [comment]
yep, exactly what Andrea said.
Are you planning on taking this on @illunix ?
Thanks for the help!

**Comment by baywet** [comment]
For the date tests, [here is what we're referring to](https://github.com/std-uritemplate/std-uritemplate/blob/95b7aceaddf3c0ccc02d0e8cf4d7c2a90b423098/typescript/test.cjs.mjs#L11)

**Comment by andreaTP** [comment]
@baywet I wanted to have a grasp of the issue and drafted #144 

I think we should re-evaluate the situation:
- There are only 4 languages with a "Native `UUID`/`GUID`" type in the standard library (C#, Java, Python, Swift)
- There is no `Guid` native type in Typescript as far as I understand it (e.g. this won't fix the originally reported issue)

At this point, I tend to think that we should fix this in the `abstractions` libraries, wdyt?

**Comment by baywet** [comment]
- Go : the vast majority of applications are using this implementation https://github.com/google/uuid
- TypeScript: the community is a bit more spread out, if we don't want to make an opiniated choice, we could just test for the present of "toString()" and call it when available.
- dart: I don't know anything about dart, sorry
- PHP: kiota is using this https://github.com/ramsey/uuid not sure how widely adopted it is but nobody has complained so far.
- Ruby: kiota is using this https://rubygems.org/gems/uuidtools not sure how widely adopted it is
- Swift: type is native

I believe we could chose to implement it here based on that analysis. The only languages (besides dart) where I could see people complaining about the choice potentially are PHP and Ruby.
But then again, if you disagree, I won't push too hard on this one, and defer it to kiota abstractions.

**Comment by baywet** [comment]
I'm usually in the camp of "break hard so it's easy to tell something is wrong", but I've received the feedback multiple times this approach can be a little drastic. So I'm open to have my mind changed on the topic.
I'll go ahead and open bugs in the kiota abstractions repositories so they can be fixed as time allows.
Once I'm done, I'll close this one as not-planned.
Thanks for the input here.

**Comment by andreaTP** [comment]
> break hard so it's easy to tell something is wrong

Agreed, let's keep going with the current approach unless we have strong reasons to change our minds 👍

**Comment by baywet** [comment]
@illunix thank you for your patience while I bounce you around the repositories here as we're trying to identify what the right course of actions is.
The next issue you'll want to engage on is this one https://github.com/microsoft/kiota-typescript/issues/1113
Please reach out there, I'll try to provide you with guidance so you can PR it and you have a fixed version quickly.
