### ISSUE TITLE
Specify an assembly file version for .NET builds

### ISSUE THREAD

**Issue by bbunt302** [std-uritemplate/std-uritemplate#154]
For at least the C# / .NET builds, it would be helpful if a `<FileVersion>` was specified in the .csproj so that the resulting DLL is tagged with an appropriate assembly file version. While the assembly file version does not have an impact on runtime, it can impact how the Windows Installer Framework handles upgrades to files.

See: https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/versioning#assembly-file-version

Note that the DLLs are currently always versioned with a default value of `1.0.0.0` as seen here:

![image](https://github.com/std-uritemplate/std-uritemplate/assets/38365920/09712fea-bebc-47a0-abef-c383c057bca3)

As the link above notes, the `<FileVersion>` value should ideally always be incremented with subsequent builds. This would mean any future version would need to be greater than `1.0.0.0`.

Here is an example of a DLL that is part of the .NET runtime:

![image](https://github.com/std-uritemplate/std-uritemplate/assets/38365920/f0f674f6-fe07-44d4-a363-959cd76ddddc)

**Comment by andreaTP** [comment]
Hi @bbunt302 thanks for your interest and finding the time to submit this issue.
I sent #155 to fix it, feel free to review it 🙏

**Comment by andreaTP** [comment]
Fixed in #155 , version 0.0.56 of the library is out, please feel free to open a new ticket or re-open this one if necessary 👍
