### ISSUE TITLE
Nuget Package should be using a license expression

### ISSUE THREAD

**Issue by thompson-tomo** [std-uritemplate/std-uritemplate#162]
### Summary
I wish for the nuget packages to have the licence expression property set correctly

### Details

The licence expression property should be set to the correct licence type I.e. Apache-2.0 as this will enable analysis of licences in use to occur in external tools & the license type will be shown in Nuget etc.

**Comment by andreaTP** [comment]
Hi @thompson-tomo and thanks for your interest in this project!

I have no objection to adding it, do you want to send a PR to fix this aspect?
cc. @baywet
