### ISSUE TITLE
Assembly file version for .NET builds cause Windows Installer upgrade issues

### ISSUE THREAD

**Issue by dukedukes** [std-uritemplate/std-uritemplate#168]
In the issue https://github.com/std-uritemplate/std-uritemplate/issues/154 it was mentioned the file version needs to be greater than 1.0.0.0, currently it's 0.0.56.0. This will cause Windows Installer to not upgrade correctly, the newer (but lower version) file won't be installed.

**Comment by andreaTP** [comment]
Thanks for taking the time to file this issue @dukedukes .

I checked and I think this is a valid issue, at the same time in the latest releases there are no code changes to the .NET implementation.
My proposed solution is to finalize the dotnet foundation affiliation and release a true `1.0.0` with signed artifacts, but open to alternatives.
@baywet what do you think?

**Comment by dukedukes** [comment]
@andreaTP Windows Installer doesn't perform same version upgrades, but if you bump the revision number (so 1.0.0.1) upgrades will succeed.

**Comment by baywet** [comment]
@andreaTP are you thinking about moving to v1 all implementations?

**Comment by andreaTP** [comment]
Yes, that's what I'm aiming for, any concern?
I'm not afraid of bumping the major when a change should happen.

**Comment by andreaTP** [comment]
I believe the version number in this repository refers to "the API and the algorithm" rather than the details of a specific implementation.

> how do you want to handle any "new or newer language" ?

as soon as an implementation is complete(it implements the same algorithm and passes all the tests) can be included in the release and gets the version number of the mainline.

> E.g. python/dart/swift have [not been reviewed on the main page](https://github.com/std-uritemplate/std-uritemplate?tab=readme-ov-file#available-implementations) and wouldn't mandate a major version yet IMHO.

Why not? The exposed API is minimal(a single method) and it's going to remain stable even after the review.
Internal changes won't break the contract we are doing with the users.

> If anybody comes up with Rust for example in the future, we'll probably want to start with a 0 major version.

If a new implementation:
- provides the same stable public API
- an implementation that conforms with the other implementations
- it passes all the tests

I feel confident enough to release 1+ major versions.

That said, I'm open to alternative suggestions 🙂 especially when we can fully automate them to keep maintenance as low as possible.

**Comment by jbettsbt** [comment]
I'm also experiencing this issue. Any chance we can get a 1.0.0.1 version sooner than later?

I could get around this uploading a 1.0.0.1 version to a private nuget repo but if a signed 1.0.0.1 is coming later I expect a worse problem down the road.

**Comment by andreaTP** [comment]
> Any chance we can get a 1.0.0.1 version sooner than later?

I'm waiting on dotnet foundation feedback, I'm sorry but this is out of my control 🙁 

Still, I do not quite grasp the issue, installing and using 0.0.55 is fine in 100% of the cases as there are no code changes in the C# implementation, am I missing something?

**Comment by jbettsbt** [comment]
@andreaTP For context this assembly has been silently failing to upgrade for some time now. We have environments with versions at least as old as 0.0.42, there was a breaking API change in 0.0.49: https://github.com/std-uritemplate/std-uritemplate/commit/3f463129fc54043a512f58ba641dc27a4262ac4c

Updating Microsoft.Graph to 5.48 (therefore Microsoft.Kiota.Abstractions to 1.8.0 and StdUriTemplate to 0.0.55) triggered missing method exceptions that led me to this issue. Microsoft.Graph was updated for compatibility reasons so I can't roll that back.

**Comment by andreaTP** [comment]
Thanks for the context @jbettsbt 👍 appreciated.
Can you confirm that upgrading manually to 0.0.55 is a viable workaround until we release a 1+ release?

**Comment by jbettsbt** [comment]
@andreaTP Yes it's possible. I'll use a custom action approach to copy 0.0.55 where needed.

**Comment by andreaTP** [comment]
@baywet I just released `0.0.59` with digital signature, if you agree we move directly to `1.0.0` (and `1.0.1` right after) to close even this issue.

**Comment by andreaTP** [comment]
Going ahead and releasing stable versions since there is no disagreement on it.

**Comment by baywet** [comment]
yep, sorry, I'm still catching up with my notifications during my vacations (still ~40/250+)

**Comment by andreaTP** [comment]
`1.0.1` just released :tada: 
Thanks everyone for the patience, let me know if everything aligns nicely now.
