### ISSUE TITLE
The License Information in pyproject.toml Does Not Match the License Information on PyPI

### ISSUE THREAD

**Issue by rakuichi4817** [std-uritemplate/std-uritemplate#201]
Based on the "pyproject.toml" file, I understand that the license for this Python library is Apache 2.0. However, on [PyPI](https://pypi.org/project/std-uritemplate/), it is listed as "Other/Proprietary." 

https://github.com/std-uritemplate/std-uritemplate/blob/b0f00de1cae3d04324fda73025b6697de7af0b5e/python/pyproject.toml#L11

This discrepancy might be due to the way the license is specified in the pyproject.toml file. It is likely that using "Apache License 2.0" or "Apache-2.0" would correctly reflect the license on PyPI. Could you please check and correct this issue ?

**Comment by andreaTP** [comment]
Thanks for taking the time to file this issue!
Fixed in #202

**Comment by andreaTP** [comment]
Fixed
![Screenshot from 2024-07-03 11-00-58](https://github.com/std-uritemplate/std-uritemplate/assets/5792097/2834db05-e542-457c-8e52-59286dc1885b)
