### ISSUE TITLE
Remove native dates support

### ISSUE THREAD

**Issue by andreaTP** [std-uritemplate/std-uritemplate#242]
Opening this Issue for visibility, starting in #239 we found a lot of rough edges in the handling of dates:

- support vary a lot across languages
- using RFC 3339 imply using Time Zones, this concept is not even present in some standard libraries (e.g. Dart) and would require additional library support
- we want to keep `std-uritemplate` as minimal as possible
- we don't want to roll our own implementation of RFC 3339
- a viable solution, for the end user, is to serialize native dates as they wish, and drop serialized strings in the substitutions map

for those(and more) reasons, we decided to remove support for native Dates and DateTime.
The removal of this feature requires a major version bump, so, the next released version is going to be 2.0.0.

**Comment by andreaTP** [comment]
@baywet @ricardoboss are we ready for the 2.0 release?
Please, have another look at the repo and let me know, I tentatively schedule the release on next Monday (30 Sept 2024).

**Comment by ricardoboss** [comment]
Code-wise it's looking good.

I noticed you aren't using the GitHub auto generated release notes and was wondering why that is? Is the workflow not working?

**Comment by andreaTP** [comment]
Thanks for the feedback @ricardoboss !

> I noticed you aren't using the GitHub auto generated release notes and was wondering why that is? Is the workflow not working?

Can you open a separate issue? What do you mean with "using"? The release notes are not stored but always re-generated.

**Comment by ricardoboss** [comment]
@andreaTP I am referring to the releases on GitHub itself, for example: https://github.com/std-uritemplate/std-uritemplate/releases/tag/1.0.6

Maybe I am not remembering correctly, but I expected the release notes on GitHub to look something like this:
![image](https://github.com/user-attachments/assets/6549e268-bfd2-43af-8af1-b8b272d54640)

and also the changelog (for Dart at least) is also not how I remembered it: https://pub.dev/packages/std_uritemplate/changelog

(I expected to see the changelog as opposed to just a link to the commits, but we may have decided against that, can't recall.)

**Comment by andreaTP** [comment]
It might be a bug ... nothing major though ...

**Comment by ricardoboss** [comment]
Yeah, this shouldn't block 2.0.

Just noticed and was interested if we can improve the workflow...
