### ISSUE TITLE
Go v2 is not available

### ISSUE THREAD

**Issue by baywet** [std-uritemplate/std-uritemplate#260]
The v2 [is currently not listed on pkg.go.dev](https://pkg.go.dev/github.com/std-uritemplate/std-uritemplate/go)

From reading the documentation, it looks like [we'd need to keep a branch in sync for that new version](https://tip.golang.org/doc/modules/major-version)

But I have no experience publishing a new major version for go libraries, so I believe we should discuss this before taking any action.

**Comment by andreaTP** [comment]
Ouch, cc. @lburgazzoli you might know on top of your head how to fix this ...

**Comment by andreaTP** [comment]
I just released `2.0.1` to fix the problem but hit another issue:

https://github.com/std-uritemplate/std-uritemplate/actions/runs/11799703853/job/32868849752#step:4:19

the good part is that we can manually finish the Go release at any point.
I'm not sure what's wrong this time, as the command works for me locally, @baywet would you find a Go expert to help out here?

We need:
- any fix required to release pipeline / docs / etc.
- the manual commands to release a proper `2.0.1`

**Comment by mikekistler** [comment]
@jhendrixMSFT might be able to help.

**Comment by jhendrixMSFT** [comment]
A version won't show up on `pkg.go.dev` until you (or somebody) `go get` it. This is documented [here](https://go.dev/doc/modules/developing#discovery).

Also, it's best practice to have the `v` prefix in your version tags. See https://go.dev/doc/modules/version-numbers for more info.

**Comment by andreaTP** [comment]
@jhendrixMSFT thanks a lot for chipping in!
This step in CI is tagging the repository for Go releases:
https://github.com/std-uritemplate/std-uritemplate/blob/ded7c2d083f759c75ff74a8adf83c07eaab9ca17/.github/workflows/release.yml#L103-L104

Unfortunately, this failed during [the last release](https://github.com/std-uritemplate/std-uritemplate/actions/runs/11799703853/job/32868849752) and I'm not sure how to fix it.

Can you, please, review the `go.mod` files in the `go` subfolder?
We are already releasing from a subfolder, is this compatible with the release of `v2` in a sub-sub-folder?
Should I run manually:

```
git tag "v2.0.1"
git tag "go/v2.0.1"
```
to fix the failed release?
In this case, will `go mod tidy` works next time?

:pray: thanks!

**Comment by jhendrixMSFT** [comment]
I've not personally tried the major version subdirectory approach for major versions, only branches. What you have looks correct though based on the [docs](https://go.dev/wiki/Modules#releasing-modules-v2-or-higher).

I believe that for major versions 2+ the `v` prefix on the tag is a requirement.

As for the tag itself, I believe it should just be `v2.x.y`. You only need to add a qualifying path when your repo contains [multiple modules that independently version](https://go.dev/doc/modules/managing-source#multiple-module-source). We do that in the `azure-sdk-for-go` repo, see some [examples](https://github.com/Azure/azure-sdk-for-go/releases).
