### ISSUE TITLE
Verify date-time usage in kiota core libraries

### ISSUE THREAD

**Issue by andreaTP** [std-uritemplate/std-uritemplate#51]
I added support for `OffsetDateTime` in Java as it was tested in the `kiota-java` repository and added a [note here](https://github.com/std-uritemplate/std-uritemplate/blob/main/Contributing.md#datetime).

We should verify if something similar is used by other languages in the Kiota core libraries.

@baywet do you have any insight to share? 🙏

**Comment by baywet** [comment]
The reason why we added it is because we have a bunch of scenarios that require it in Microsoft Graph including [this one](https://learn.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&tabs=http)
Let me know if you need anything else

**Comment by andreaTP** [comment]
Thanks for getting back!
This would probably mean that we have to extend the support for date-time formats to all of the languages and have them tested in CI.

**Comment by baywet** [comment]
What might be worth checking is whether we get the string representation before we add the parameter to the URI template

**Comment by andreaTP** [comment]
yup, on it 👍
