### ISSUE TITLE
Review the PHP implementation

### ISSUE THREAD

**Issue by andreaTP** [std-uritemplate/std-uritemplate#54]
@silaskenneth and @Ndiritu would be great if you could review the PHP implementation 🙏

**Comment by Ndiritu** [comment]
@andreaTP I'm unable to assign myself the linked issues. Happy to work on them. Will log more as I dig further into the implementation.

**Comment by andreaTP** [comment]
@Ndiritu , assigned, thanks!

**Comment by andreaTP** [comment]
@Ndiritu do you think that this library meets the standard now?

**Comment by Ndiritu** [comment]
> @Ndiritu do you think that this library meets the standard now?

Yes. Added some minor enhancements and fixes.
