### ISSUE TITLE
Add digital signature to NuGet package

### ISSUE THREAD

**Issue by SteveDinn** [std-uritemplate/std-uritemplate#74]
I have found this project as a result of adding the Microsoft.Graph NuGet package to my application, and noticing that the transitively-referenced Tavis.UriTemplates NuGet package contained assemblies that were not digitally signed. Are there plans to include a digital signature on the DLL in *this* package? For all the reasons listed in the original issue here, https://github.com/tavis-software/Tavis.UriTemplates/issues/105, I believe that there should be.

As a temporary stopgap measure, do the terms of the Apache license prevent me from using my own certificate to sign the files from the NuGet package? I realize that it is generally bad form to impose one's digital signature on somebody else's work and that the entire point of digitally signing things is to verify that components originate from the intended source. However, the only alternative that I see is regressing to an older version of Microsoft.Graph, and I'd rather not do that if I can help it.

Thanks!

**Comment by andreaTP** [comment]
Hi @SteveDinn , and thanks for your interest in this library!

> Are there plans to include a digital signature on the DLL in this package?

We have discussed it already and there are conversations going on, unfortunately we don't have a plan just yet.

> As a temporary stopgap measure, do the terms of the Apache license prevent me from using my own certificate to sign the files from the NuGet package?

If I understand it correctly and you want to sign the files for your own usage, there should be no limitation.
If you want to share the procedure for doing so I'll happily integrate it into the docs!

Cc. @baywet

**Comment by baywet** [comment]
As a precision @SteveDinn did you have a reference to Microsoft Graph before? if so which version? Wasn't it the same issue for you with Tavis.UrlTemplate?

For reference we're talking about multiple things here:
- The assembly is already strong name signed.
- The assembly needs to be [digitally signed with a valid certificate](https://learn.microsoft.com/en-us/dotnet/framework/tools/signtool-exe#sign)
- The nuget package needs to be [digitally signed with a valid certificate](https://learn.microsoft.com/en-us/nuget/create-packages/sign-a-package)
(step 2 and 3 can use the same certificate)

The challenges being:
- We can't sign things using Microsoft's signing infrastructure if the GitHub organization is not an enterprise organization managed by Microsoft (SSO, MFA, compliance tooling, etc...). This would also require the package name to start with Microsoft or Azure.
- We can't buy certificates using Microsoft's name (centrally managed by the security team)
- This organization doesn't have it's own legal organization (corp/organization/foundation), it can't get certificates to sign things in its name, and setting up a legal entity seems like a huge overhead.

That doesn't leave us with a lot of options:
- Either Red Hat has more lax rules in terms of code signing and we can rely on their sign in infrastructure. (@andreaTP  can you check internally)
- Or we sign as an individual (is it even allowed anymore?) and expense the certificate. But is that going to increase trust?
- We setup some kind of mirroring of the repository internally and publish a signed version under Microsoft. (in that case should we remove this one from listing?)

**Comment by SteveDinn** [comment]
I am referencing Microsoft.Graph in this product for the first time as of this week. I then:
- noticed the lack of digital signature in the Tavis.UrlTemplate package
- found the issue logged in their repo
- Explicitly referenced the Microsoft.Kiota.Abstractions package that instead referenced Std.UrlTemplate

And here I am.

You've certainly explained the situation well enough. I understand the obstacles.

Maybe in the absence of the digital signatures, the project could publish some hash values for the .nupkg file and/or the files within. If there were some way to validate the authenticity of the files, it would be better than nothing.

**Comment by baywet** [comment]
Thanks for the additional context here. I'm guessing your goal is to protect yourself from a potential hostile account take over on nuget.org?
Do you typically keep track of the certificate thumbprints or so over time? And warrant an investigation if something changes? or do you do something else?

**Comment by SteveDinn** [comment]
That's pretty much exactly what we do. Any time we add or update a package, we'll also update the list of known certificate thumbprints. I'm just looking for some way in which we can do the same kind of tracking with this package.

**Comment by baywet** [comment]
what do you do when the thumbprint changes?

**Comment by SteveDinn** [comment]
If we updated something on our end, and expect the thumbprint to change, then no big deal.
If it changed from what we expected, then I'd investigate what happened. Why would a previously-built package suddenly have a new signing certificate thumbprint? That generally doesn't happen.

**Comment by baywet** [comment]
when you update a package, how do you tell the difference between "the owner has rotated the key and the change is legit" and "the package has been compromised" ?

**Comment by SteveDinn** [comment]
I would expect that the creator of the package would have let people know that the signing certificate has been updated. When I notice on my end that the thumbprint has changed, I would go and look for such an announcement, perhaps on the github page of the package, or wherever it was hosted. If I couldn't find such an announcement, I would probably raise an issue with the package creator to get my question answered.

Is this going somewhere? Am I actually influencing policy here?

**Comment by baywet** [comment]
Thanks for all the information and for your patience.

Yes you are, as the policy still needs to be defined for this organization.

I'm trying to get a good understanding of what problems you are solving and how using signed packages in case we come up with an alternative.

Last question: is a package signed by an organization that's not a major software editor (e.g. Microsoft, red hat, etc) a red flag to your workflow or is it considered normal?

**Comment by SteveDinn** [comment]
It's not necessarily a red flag, but it would definitely be an oddity. 

There have been other NuGet packages that we've consumed that weren't signed, and we've ended up building them and signing them ourselves. However, with this package being at the bottom of the dependency chain of Microsoft.Graph, we'd have to build *everything* (Microsoft.Graph.\*, Microsoft.Kiota.\*), which would be a giant pain and is not something I really want to do if it can be avoided.

**Comment by baywet** [comment]
Perfect. Thanks again for all the feedback. We'll wait for @andreaTP to revert on whether we can use red hat signing infrastructure for this and consider our options. (He is out these days, expect a little delay)

**Comment by andreaTP** [comment]
Thanks a lot for this great conversation @SteveDinn and @baywet !

@SteveDinn can I ask if you have already had any conversation like this on the OpenTelemetry side (which is affected by the very same problem AFAIK)?
They have reached some conclusions [here](https://github.com/open-telemetry/opentelemetry-dotnet/issues/1302#issuecomment-1126841168) but I don't know how this applies to your use case.

Let me try to summarize the options:

- **publish through Microsoft infrastructure** - We created a separate organization in the spirit of detaching "company strings", I won't oppose if this is the only viable solution but it would be suboptimal and we would need to clear a bunch of unknowns
- **Red Hat singing infrastructure** - This is not an option on the table, Red Hat does have a lot of tooling for Java and more, but, as far as I understand it, there is no support for dotnet as of today. I started the conversation internally but that's it.
- **sign as an individual** - this is definitely possible, would it be a viable solution? The challenge would be to keep the certificate renewed, but should not be a blocker.
- **the project could publish some hash values** - This is definitely possible, publishing a SHA or MD5 of the assemblies in GH releases gives the user 2 sources (GH and NuGet) they can cross-check for authenticity. The problem with this approach is that there is no "already available" tooling(I'm aware of) to support the approach.

**Comment by andreaTP** [comment]
A quick follow-up from [my today's reading](https://haacked.com/archive/2019/04/03/nuget-package-signing/)>
- there are individual certificates available for free for Microsoft employees https://www.digicert.com/friends/msmvp/
- [dotnetfoundation](https://dotnetfoundation.org/about) offers certificates to affiliated projects

The "dotnetfoundation" option seems to be great, but I'm not sure about the extent of their CLA, and I would like to not impose it on contributors (especially for different languages).

**Comment by baywet** [comment]
@andreaTP maybe we could setup a separate repo for just the dotnet package. And have it sync here for releases. But maintain the source there. This we we could join the dotnet foundation just for that package, and avoid "contaminating" other packages with dotnet foundation requirements.

**Comment by baywet** [comment]
Reached out to the foundation: no, I was waiting for your input first.

I forgot to mention that I tried the digicert MS employee option, and they are charging for the code sign kind of certificate. I've reached out to them to see if they could do something about that. Waiting to hear back.

The "source of truth" for the code needs to be where the CLA check will be setup, this is to ensure no code without the CLA ever makes it to the source base to avoid future potential litigations as far as I understand. If it's the same check we have at Microsoft, there's no way to enforce it only for selected paths of the repo.

**Comment by andreaTP** [comment]
Thanks for getting back @baywet !

> If it's the same check we have at Microsoft, there's no way to enforce it only for selected paths of the repo.

I do believe that this is pretty limiting and not welcoming for Open Source projects 🙁 , maybe we can share our thoughts and see if they are flexible.

If you wanna contact the dotnet foundation feel free to go ahead and keep me in the loop (private email).

**Comment by baywet** [comment]
Started a thread [here](https://github.com/dotnet-foundation/projects/discussions/338)

**Comment by andreaTP** [comment]
Quick update, if you @baywet don't have "urgency" I might be able to get to the bottom of this (with keys provided by RH) with in a relaxed time-frame, i.e. ~early Q1 next year.

**Comment by baywet** [comment]
That'd be great news!
I'm still trying to figure things out internally. I've reached out to our legal team, we'll see what they come up with but so far all other solutions are pretty heavy handed (move under Microsoft org, move under Red Hat org, join the dotnet foundation...)
There are some that are a bit more lightweight: copy the std URL template in the kiota abstractions (keep it in sync), cross publish std.uritemplate under a new Microsoft package through some sync and automation.
But none of those are "easy fixes" that'll quickly solve the issue. So keep your discussions going on the Red Hat side, I'll keep mine on Microsoft's side and the first to have a concrete solution wins. :)
I should be able to keep the service teams on our side at bay for now, but it's pressing.

**Comment by andreaTP** [comment]
Agreed 👍 🙂

**Comment by baywet** [comment]
Just an update on the digicert option: after going back and forth with them, the code-sign certificate is offered at a discount but not for free as we suspected (250US instead of 530). So we should probably rule this out as an option since even though the cost is not huge, we might not be able to renew it in the future.

**Comment by baywet** [comment]
submitted a request to join the dotnet foundation https://github.com/dotnet-foundation/projects/issues/349

**Comment by yihezkel** [comment]
What's the status of getting this package signed? It's blocking us from upgrading to Graph v5, which is becoming increasingly urgent.

**Comment by andreaTP** [comment]
@yihezkel currently we are waiting on this: https://github.com/dotnet-foundation/projects/issues/370 hopefully we will get an answer in a few days ...

**Comment by andreaTP** [comment]
Update that, despite the extreme slowness, we have not dropped the ball on this issue and we are going to be, eventually, part of the dotnet foundation (therefore able to sign the package):
https://github.com/dotnet-foundation/projects/issues/353#issuecomment-2047475639

**Comment by andreaTP** [comment]
This one is finally fixed thanks to the DotNet Foundation!

![Screenshot from 2024-06-07 14-16-49](https://github.com/std-uritemplate/std-uritemplate/assets/5792097/909cfa60-4a35-475f-a9a1-a75c76efa27f)

:tada:

**Comment by yihezkel** [comment]
Thanks so much for your efforts on this, @andreaTP and @baywet!

Vincent, will a new version of `Microsoft.Graph` be released soon that includes only signed artifacts?

**Comment by baywet** [comment]
@yihezkel sure! As you can see a new version of kiota abstractions has already been released on that dependency. Next step the microsoft graph core library, and then the service (generated) libraries for beta and v1.
https://www.nuget.org/packages/Microsoft.Kiota.abstractions#dependencies-body-tab

**Comment by baywet** [comment]
actually, the core library already uses a range, so you should be able to get everything working with signature right now.
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/638c9809249facd40f2ea39ccdbc06ec88928c3d/src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj#L62

**Comment by yihezkel** [comment]
@baywet @andreaTP 
We're using Microsoft.Grpah v5.65 / Microsoft.Kiota.Abstractions v1.15.2 / Std.UriTemplate v2.0.1, and our builds are failing on:
##[error]1. CodeSign Error CodeSign.NoMatchingPolicy - File: Std.UriTemplate.dll.

**Comment by andreaTP** [comment]
Hi @yihezkel and thanks a lot for the report!

Looking at the package detail in NuGet everything looks correctly signed, also the log of the release shows that packages are correctly signed too:
https://github.com/std-uritemplate/std-uritemplate/actions/runs/11799703853/job/32868932877#step:7:28

Since this is a closed issue it might not receive enough visibility, I invite you to open a new one with the steps to reproduce the issue.

**Comment by baywet** [comment]
@andreaTP thanks for taking the time to reply here, this is actually coming from an internal Microsoft thread.
Their policy engine is failing because the name of the certificate signer is "std.uritemplate (.NET Foundation)" instead of ".NET Foundation" which has a blanket approval internally.
I believe we're caught between two sets of policies (how DNF emits the certificates has changed, and Microsoft's internal validation policy does not account for that)

The only question I have for you is: do you remember choosing the name at any point? I certainly don't remember asking for a specific name.

With that, I'll follow up on the internal thread in a few minutes, and revert here if anything needs to be done.

**Comment by andreaTP** [comment]
> do you remember choosing the name at any point?

I just checked the email threads with DNF and I confirm we have not been asked for the name in the certificate at any point in time.

Sorry to hear that this is still causing headaches :sweat:
