### ISSUE TITLE
PHP - Fatal Error when running extended tests

### ISSUE THREAD

**Issue by Ndiritu** [std-uritemplate/std-uritemplate#76]
`./tests/test.sh php extended-tests.json` fails after "'Additional Examples 2" with

`PHP Fatal error:  Cannot redeclare stduritemplate\array_is_list() (previously declared in /home/ndiritu/projects/std-uritemplate/php/src/StdUriTemplate.php:296) in /home/ndiritu/projects/std-uritemplate/php/src/StdUriTemplate.php on line 296`

part of https://github.com/std-uritemplate/std-uritemplate/issues/54

**Comment by andreaTP** [comment]
This is really strange, the tests are passing locally and in CI:
https://github.com/std-uritemplate/std-uritemplate/actions/runs/6246797869/job/16958105872#step:13:27

would you mind providing more context about your environment, PHP version etc. to try to narrow this down?

**Comment by Ndiritu** [comment]
This fails on PHP 7.4 running on WSL Linux.
`array_is_list` is introduced as a built-in function from PHP 8.1 onwards. Our CI runs on PHP 8.2.
Trying to troubleshoot further.

**Comment by andreaTP** [comment]
Thanks for the feedback @Ndiritu , apparently this "polyfill" is not working as expected:
https://github.com/std-uritemplate/std-uritemplate/blob/7dba309cd2f35498784a3e84217dfc47090c54c9/php/src/StdUriTemplate.php#L294

I'll leave this one with you, but, if you have any trouble, please, just ping me back 👍

**Comment by Ndiritu** [comment]
> Thanks for the feedback @Ndiritu , apparently this "polyfill" is not working as expected:
> 
> https://github.com/std-uritemplate/std-uritemplate/blob/7dba309cd2f35498784a3e84217dfc47090c54c9/php/src/StdUriTemplate.php#L294
> 
> I'll leave this one with you, but, if you have any trouble, please, just ping me back 👍

Sure. Will do.

**Comment by andreaTP** [comment]
@Ndiritu I ended up looking at the problem and proposed a solution in #79 let me know what you think about it!

**Comment by andreaTP** [comment]
fixed in #79
