### ISSUE TITLE
PHP - Specify minimum supported PHP version?

### ISSUE THREAD

**Issue by Ndiritu** [std-uritemplate/std-uritemplate#77]
Composer.json doesn't specify a minimum support php version.

- Check implication of not specifying a minimum version
- What's our desired minimum supported version?

part of https://github.com/std-uritemplate/std-uritemplate/issues/54

**Comment by andreaTP** [comment]
I'm not a PHP expert, but I'm happy to specify a minimum version as soon as we can find a suitable number.
Do you have a suggestion?

**Comment by Ndiritu** [comment]
I'd recommend 7.4 based off [usage stats](https://packagist.org/php-statistics). Although it's no longer [officially supported](https://www.php.net/supported-versions.php) this should capture PHP 7 apps yet to transition and eventually we can major rev and bump the minimum to PHP 8.

Kiota PHP is built for PHP 7.4 minimum and hopefully a major rev will allow us to produce PHP 8 SDKs.
